[package]
name = "valinor-sif"
version = "0.1.0"
edition = "2024"

[dependencies]
pathfinding = "4.14.0"
serde_json.workspace = true
valhalla-graphtile = { path = "../valhalla-graphtile", features = ["serde"] }

[lints]
workspace = true
